### ISSUE TITLE
Unable to run the panda capsule example

### ISSUE THREAD

**Issue by xueminchi** [tud-amr/fabrics#102]
Hi @maxspahn ,

The error message is under below:
```
Traceback (most recent call last):
  File "/home/cxm/PycharmProjects/fabrics/examples/panda_capsules.py", line 181, in <module>
    res = run_panda_capsule_example(n_steps=5000)
  File "/home/cxm/PycharmProjects/fabrics/examples/panda_capsules.py", line 148, in run_panda_capsule_example
    planner = set_planner(goal)
  File "/home/cxm/PycharmProjects/fabrics/examples/panda_capsules.py", line 129, in set_planner
    tf_capsule_origin =  forward_kinematics.casadi(
  File "/home/cxm/anaconda3/envs/fabrics/lib/python3.9/site-packages/forwardkinematics/**urdfFks/generic_urdf_fk.py**", line 59, in casadi
    if positionOnly:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

```
if positionOnly:
    fk = fk[0:3, 3]
return fk
```

@xueminchi

**Comment by xueminchi** [comment]
Hi @maxspahn ,

The python version is `Python 3.9.17 (main, Jul  5 2023, 20:41:20) `
`import forwardkinematics` works fine, but `forwardkinematics.__version__` caused an issue as below
`AttributeError: module 'forwardkinematics' has no attribute '__version__'`

@xueminchi

**Comment by maxspahn** [comment]
Ok, can you do `pip show forwardkinematics` instead then?

**Comment by xueminchi** [comment]
> 
Sure. 
`Name: forwardkinematics
Version: 1.1.1
Summary: "Light-weight implementation of forward kinematics using casadi."
Home-page: https://github.com/maxspahn/forwardKinematics.git
Author: Max Spahn
Author-email: m.spahn@tudelft.nl
License: MIT
Location: /home/cxm/anaconda3/envs/fabrics/lib/python3.9/site-packages
Requires: casadi, numpy, urdf_parser_py
Required-by: fabrics, planarenvs
`

`Name: planarenvs
Version: 1.4.0
Summary: Lightweight open-ai gym environments for planar kinematic chains.
Home-page: 
Author: Max Spahn
Author-email: m.spahn@tudelft.nl
License: 
Location: /home/cxm/anaconda3/envs/fabrics/lib/python3.9/site-packages
Requires: forwardkinematics, gym, mpscenes, numpy, pygame, pyglet, pylint, scipy
Required-by: 
`

**Comment by maxspahn** [comment]
Ok, you need at least version 1.1.3. But the installation should have taken care of that. The pyproject.toml file must be changed so that forwardkinematics=^1.1.3. I'll try to do that tomorrow

**Comment by maxspahn** [comment]
Any news on that, @xueminchi ?

**Comment by xueminchi** [comment]
> Any news on that, @xueminchi ?

I change the pyproject.toml file locally as you mentioned and it works good. @maxspahn

**Comment by maxspahn** [comment]
ok, great. I'll make the changes then.
