### ISSUE TITLE
The size of the 'boxer chassis'.

### ISSUE THREAD

**Issue by xueminchi** [tud-amr/fabrics#104]
Hi @maxspahn ,

I've finished the simple tests on point robot and panda robot considering any shapes. I'm working on non-holonomic robots now. I try to add some visualizations but I don't know the size of the 'boxer', the size of 'chassis_link'. Where I can get the information?

best,
@xueminchi

**Comment by maxspahn** [comment]
You have to look in the URDF file I think. The wheel distance should be given in the instantiation of the URDF environment.

**Comment by xueminchi** [comment]
> You have to look in the URDF file I think. The wheel distance should be given in the instantiation of the URDF environment.

Thanks! I get the size information from the meshes STL file and the wheel distance in URDF file.
