### ISSUE TITLE
poetry environment

### ISSUE THREAD

**Issue by saraybakker1** [tud-amr/fabrics#112]
I made a new fork of the fabrics develop branch. 
To make the poetry environment work, I still had to install urdfenvs manually via: poetry run pip install urdfenvs.

**Comment by maxspahn** [comment]
To install urdfenvs, you have to install with the optional group agents.

**Comment by maxspahn** [comment]
More specifically with `poetry --with agents`.

Let me know if that worked for you, @saraybakker1
