### ISSUE TITLE
Breaking change in newest version due to ForwardKinematics=1.2.0

### ISSUE THREAD

**Issue by saraybakker1** [tud-amr/fabrics#128]
Hi Max, the newest version of ForwardKinematics=1.2.0 causes an error in (as far as I know) all examples on the develop branch.

ModuleNotFoundError: No module named 'forwardkinematics.fksCommon.fk_creator'

I didn't examine the problem that well for all cases, but for me it worked to limit to maximal forwardkinematics==1.1.5

**Comment by maxspahn** [comment]
Indeed, that is a problem, as the version of forward kinematics is not limited. 
Thanks for letting me know.
