### ISSUE TITLE
env.reset() cannot happen after goal is defined

### ISSUE THREAD

**Issue by saraybakker1** [tud-amr/fabrics#87]
When I would like to reset the environment (to for example run as second experiment), this is not possible, because the goal is already defined. I will get the error:
AttributeError: 'GoalComposition' object has no attribute 'position'
This is quite impractical for running multiple experiments in one script with 1 environment (also for RL).

**Comment by maxspahn** [comment]
Isn't that rather a problem of [urdfenvs](https://github.com/maxspahn/gym_envs_urdf)?
Can you provide a minimal example for that?
