### ISSUE TITLE
plane constraint

### ISSUE THREAD

**Issue by saraybakker1** [tud-amr/fabrics#91]
if I select one of the last links for obstacle avoidance (panda_link_8), the planar constraint seems to be overconservative. Therefore the block on the ground cannot be reached. The panda_hand link (for goal reaching) stops at around 25 cm above the ground. 
If for example panda_link_3 is only considered for obstacle avoidance, this is not an issue. 

![screenshot_planar_constraints](https://github.com/tud-amr/fabrics/assets/118430816/f458572b-456b-4b0f-99b7-b3a188c716d5)

**Comment by maxspahn** [comment]
You can adjust the geometry and the finsler energy to your needs, but the constraint itself should not be changed, I would say.
