### ISSUE TITLE
Confirming the Correct Process for Contributing to Fabrics

### ISSUE THREAD

**Issue by xueminchi** [tud-amr/fabrics#95]
Hi @maxspahn,

I want to contribute to Fabrics, but I'm not entirely sure if the steps I'm planning to follow are correct. As I'm not very familiar with GitHub, could you please review them? I'm sharing these steps here in case there are other people in the same situation as me.

First, I plan to fork the repo and then clone it to my local server. This will allow me to develop locally. Once I've completed and checked my work, I intend to initiate a pull request to you.

Could you please confirm if this process is correct? Or is there another preferred method?

Best,
@xueminchi

**Comment by maxspahn** [comment]
Hi @xueminchi ,

Great talking to hear and even better reading that you want to contribute to that project 🔥 .

The steps you described are exactly right. A more detailed explanation/guide can be found at [first-contributions](https://github.com/firstcontributions/first-contributions).

I suggest you start with a very simple improvement of one specific tutorial file, or the adding of one tutorial file. As soon as you have something to share with me, you can create a pull request form your branch on your fork to the develop branch of this repository. In the discussion for that PR, we can discuss the details then.

Looking forward to working with you.

@maxspahn

**Comment by xueminchi** [comment]
Hi @maxspahn ,

Thank you very much for your quick response and for confirming the process. I greatly appreciate your guidance and the tutorial you shared; it will be very helpful as I start my contribution to the project.

I will begin by focusing on a specific tutorial file, as you suggested. Once I have something ready, I'll create a pull request from my branch on my fork to the develop branch of this repository.

I'm looking forward to working with you as well and contributing to Fabrics.

Best,
@xueminchi

**Comment by maxspahn** [comment]
There should be a Contributing-file.
