### ISSUE TITLE
Issues with Color Rendering and Script Execution in 'examples' 

### ISSUE THREAD

**Issue by xueminchi** [tud-amr/fabrics#96]
Hi @maxspahn ,

I have forked Fabrics and created a new local environment for it. When manually running files in 'examples' and 'tutorials', I encountered some issues, as described below:

1. The color of the obstacles has changed to black instead of red.
2. When I run **point_robot_esdf** directly, I receive the following errors. This didn't happen before and I suspect it's due to def test_edf_evaluation(proj_rgb):. Initially, I installed pytest and attempted to run it, but this only led to more error messages. Commenting out the code seems to solve the problem temporarily.
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pytest'

Additionally, it seems like the package 'plt' isn't imported even though some codes are using it.
`    if logging.root.level <= 10:
        plt.subplot(1, 2, 1)
        plt.imshow(proj_rgb)
        plt.subplot(1, 2, 2)
        plt.imshow(proj_depth)
        plt.show()
        test_edf_evaluation(proj_rgb)`

3. For the file **point robot urdf passage**, In the file point_robot_urdf_passage, the following code doesn't work, producing error messages regardless of whether the value is 0 or 1. Modifying the line to `res = run_point_robot_urdf(n_steps=6000, render=True)` seems to make it work fine.
`   import sys
    res = run_point_robot_urdf(n_steps=6000, render=bool(int(sys.argv[1])))
`

@xueminchi

**Comment by maxspahn** [comment]
@xueminchi 

To point 1), the color can be changed by changing the obstacle description. This is due to a change in the mpscenes package.

To the other points, I created individual issues. It is hard to keep track if issues if multiples are mentioned under the same hashtag.
